name=Serial Manager
version=1.0.0
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=Pustaka parser komunikasi serial non-blocking dengan manajemen memori efisien untuk Arduino.
paragraph=Menyediakan pembacaan data serial tanpa penundaan (non-blocking delay) dan pemecahan argumen (parsing) otomatis menggunakan referensi memori (zero-copy). Arsitektur ini dirancang secara khusus untuk mencegah kebocoran dan fragmentasi RAM pada mikrokontroler bermemori terbatas.
category=Communication
url=https://github.com/pengguna/Serial_Manager
architectures=*
includes=Serial_Manager.h